### PR TITLE
People page revamped

### PR DESCRIPTION
**Pull request by geekSiddharth**
#95 #100

### CODE REVIEW

**Comment by geekSiddharth** [comment]
"Chairman on a separate line like it was before" - It will make the design inconsistent.

**Comment by tarelli** [comment]
You mean because we are not always using it? 
screen shot 2017-06-29 at 10 33 08
It's probably subjective but I find the above more aesthetically pleasing than the inlined version.

**Comment by geekSiddharth** [comment]
Yup! I agree it is subjective. In this case, it looks like this:

image

**Comment by tarelli** [comment]
What about this? Smaller vertical spacing, icons aligned.
screen shot 2017-06-29 at 10 41 56

**Comment by tarelli** [comment]
Also better to crop Lucy's picture around the head for consistency 
screen shot 2017-06-29 at 10 44 21

**Comment by geekSiddharth** [comment]
Changes mentioned in the review have been made.

**Comment by MichaelCurrie** [comment]
If it's possible to add Paul Gibson's picture with the title Board Secretary that would be great.

(same as how Ryan is "Chairman")

e457f5a6-9522-4057-acde-bff4a53c99aa 1

**Comment by geekSiddharth** [comment]
@MichaelCurrie  Done! 

image

**Pull request merged**
