### PR TITLE
Embedded TEDx talks in Media. "See OpenWorm" and TEDx links added on homepage

### PR DESCRIPTION
**Pull request by geekSiddharth**
TEDx talk videos were embedded in the homepage. Solved #107 
UI of the homepage was made more consistent on the basis of css class "marketing".

The media coverage section and TEDx icon/section was combined.
image

### CODE REVIEW

**Comment by tarelli** [comment]
Thanks @geekSiddharth as per today's discussion might be better to move the videos to the media page and link that from the TEDx logo

**Comment by geekSiddharth** [comment]
Is this fine?

**Comment by geekSiddharth** [comment]
Is this fine?

Media Page
image

Homepage
image

**Comment by MichaelCurrie** [comment]
Looks great to me; added @tarelli as reviewer.

**Comment by tarelli** [comment]
@geekSiddharth Two logos going to the same place looks visually redundant, how about one logo with caption being something like "Bangalore and Vienna"?

**Comment by geekSiddharth** [comment]
Initially, I did exactly what you have mentioned. I was trying to recreate a respectiveTEDx logo(like that of TEDxBangalore). But I faced some problems. 

The best approach would be to replace them with their respective TEDx logo. (I tried finding them. But didn't find one that I can use ) Someone with Photoshop skills will be required.

**Comment by tarelli** [comment]
Yeah TEDx don't really have a logo, they just write the name of the city next to the TEDx logo, I think it's fine to have just one TEDx logo with the caption to account for both cities.

**Comment by geekSiddharth** [comment]
image
 
Is this fine?

**Comment by tarelli** [comment]
screen shot 2017-06-19 at 21 15 54

**Comment by MichaelCurrie** [comment]
Looks great @geekSiddharth.  Merged.

**Pull request merged**
